version: '3.8'

services:
  jupyterhub:
    build: hub_image
    image: hub
    container_name: jupyterhub
    depends_on: [notebook]
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jupyterhub

  notebook:
    image: jupyter/base-notebook:hub-1.1.0
    
# the actual name will be <directory_name>_<network_name>
networks:
    jupyterhub:
      driver: bridge

volumes:
  jupyterhub_data:

