version: '3.8'

services:
  jupyterhub:
    build: hub_image
    image: hub
    container_name: jupyterhub
    depends_on: [notebook]

  notebook:
    image: jupyter/base-notebook
    
# the actual name will be <directory_name>_<network_name>
networks:
    jupyterhub:
      driver: bridge

volumes:
  jupyterhub_data:

